const
  TPilot* = "خلبان"
  TCost* = "مبلغ"
  TOrigin* = "مبدا"
  TDest* = "مقصد"
  TBuy* = "خرید"
  TCompany* = "شرکت"
  TInternationalCode* = "کد ملی"
  Tfly* = "پرواز"
  TDate* = "تاریخ"
  Tid* = "شناسه"
  Ttime* = "زمان"